apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pathfinder-ingress
  namespace: "2401019"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: 2401019.imcc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pathfinder-service
            port:
              number: 3000
